# -*- coding: utf-8 -*-
"""1° trabalho - python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QWzG9GIREUeU1V9yz1MVLi-IjalBop_p

1. Entrar com um número e imprimi-lo caso seja maior que 20
"""

x=input()
if float(x)>20:
  print(x)

"""2. Entrar com um número e imprima uma das mensagens: é múltiplo de 3 ou não

"""

x=input()
x= int(x)

if x % 3==0:
  print("é múltiplo")
else:
  print("não é múltiplo")

"""3. Entrar com um número e informar se ele é divisível por 3 E por 7"""

x=input()
x= int(x)

if x % 3==0 and x % 7==0 :
  print("é divisível")
else:
  print("não é divisível")

"""4. Fazer um algoritmo que possa entrar com o saldo de uma aplicação e imprima o novo saldo, considerando o reajuste de 2%"""

x= input()
x= float(x)
y= x*1.02
print(y)

"""5. Imagine que você foi contratado por uma faculdade para criar um sistema de lançamento de notas para os professores, pensando em ajudar os colegas, quando um aluno fica com nota 6,5 ela é automaticamente arrondada para 7. Como isso pode ser feito? Crie um algoritmo que receba a nota e imprima a nova nota."""

x= input()
x= float(x)

if x==6.5:
  x=7
  print(x)
else:
  print(x)

"""6. Crie uma calculadora que receba a operação, o valor do número 1, o valor do número 2 e imprima o resultado. Considere as 4 operações básica."""

print("insira a operação")
print("1-Multiplicação")
print("2-Subtração")
print("3-Soma")
print("4-Divisão")
x= float(input())
print("Primeiro valor")
y= float(input())
print("Segundo valor")
z= float(input())

if x==1:
  print(y*z)
if x==2:
  print(y-z)
if x==3:
  print(y+z)
if x==4:
  print(y/z)

"""7. Peça via input para o usuário o nome e o sexo, caso seja idade seja igual a 18, e sexo masculino, coloque a mensagem: 'Serviço militar obrigatório', caso contrário, 'liberado do serviço militar obrigatório'"""

print("Qual o seu nome?")
nome=input()
print("Qual o seu sexo?")
print("1-Masculino")
print("2-Feminino")
x=input()
print("Qual a sua idade?")
y=float (input())
if x=="1" and y==18:
  print("Serviço militar obrigatório")
else:
  print("Liberado do serviço militar obrigatório")

"""8. Faça um programa que receba o salário atual de um funcionário e calcule o valor do imposto que ele deve pagar conforme tabela abaixo:
 - Até 500 reais, não paga nada
 - De 500,01 até 1.000,00 - paga 5% de imposto
 - De 1000,01 até 1500,00 - paga 7% de imposto
 - Acima de 1500,01 - paga 10% de imposto
"""

print("Qual o seu salário?")
x= float (input())

if x<=500:
  print("Valor de imposto a pagar:")
  print("Não paga nada")
if x>=500.01 and x<=1000:
  print("Valor de imposto a pagar 5%:\n" + "R$" + str(x*1.05))
if x>=1000.01 and x<=1500:
  print("Valor de imposto a pagar 7%:\n" + "R$" + str(x*1.07))
if x>=1500.01:
  print("Valor de imposto a pagar 10%:\n" + "R$" + str(x*1.1))

"""9. Faça um programa que mostre uma mensagem conforme a faixa etária dos usuários:
 - Até 18 anos - menor de idade
 - Acima de 65 anos - clube nissei
 - Entre 19 e 65 - adulto ativo
"""

print("Qual a sua idade?")
idade=int (input())
if idade <=18:
  print("Menor de idade")
if idade>65:
  print("Clube nissei")
if idade >= 18 and idade <= 65:
  print("Adulto ativo")

"""10. Faça um programa que pergunte se o usuário possui irmãos, em caso positivo, pergunte quantos irmãos ele tem."""

print("você tem irmãos?")
print("1-sim")
print("2-não")
x=input()
if x=="1":
  print("quanto irmãos você tem?")
  y=input()